### ISSUE TITLE
UX for request access page [categories section]

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#215]
WHAT IS THE ISSUE?
The category field of the form for request access is not very user friendly.

SCREENSHOT?
![image](https://user-images.githubusercontent.com/1590213/114262746-4b521680-99ea-11eb-8d54-fcb4f87edfcb.png)

**Comment by ja-odur** [comment]
This is resolved by this [PR](https://github.com/airqo-platform/AirQo-frontend/pull/216)

**Comment by Baalmart** [comment]
> This is resolved by this [PR](https://github.com/airqo-platform/AirQo-frontend/pull/216)

For some reason, the latest deployments for both staging and production still have the same issue yet the [PR](https://github.com/airqo-platform/AirQo-frontend/pull/216) was merged. I am now wondering.....

**Comment by danielogen** [comment]
> > This is resolved by this [PR](https://github.com/airqo-platform/AirQo-frontend/pull/216)
> 
> For some reason, the latest deployments for both staging and production still have the same issue yet the [PR](https://github.com/airqo-platform/AirQo-frontend/pull/216) was merged. I am now wondering.....

Hi @Baalmart , staging frontend wasn't re-deployed yesterday but now should be fine. For production environment, looks like the changes never made it to the master. We might have to merge the latest staging to production.

**Comment by ja-odur** [comment]
This has been fixed
